### ISSUE TITLE
css.gg icon scaling

### ISSUE THREAD

**Issue by astrit** [nottombraider/mytodo#5]
I saw you are using css.gg for the icons and thanks for that. 
However noticed that you created a new class to resize them. 

If you wish to resize one icon or all of them you just have to add this CSS variable to the parent or directly to the icon 

```css
.gg-add {
   --ggs: 5;
}

/* this will multiply the actual size and it can be any number of course*/
```

Sorry for writing here. 
✌
